server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  grpc:
    server:
      port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}